server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devconnect
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
  config:
    import: optional:.env

logging:
  level:
    org.springframework.security: DEBUG