version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: devconnect-pstgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: devconnect
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: